# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Release Essentials
      run: dotnet build --no-restore --configuration Release_BasicVersion
    - name: Test Release Essentials
      run: dotnet test --configuration Release_BasicVersion --no-build --verbosity normal
    - name: Build Release
      run: dotnet build --no-restore --configuration Release
    - name: Test Release Essentials
      run: dotnet test --configuration Release_BasicVersion --no-build --verbosity normal
