
name: publish
on: workflow_dispatch

env:
  NuGetDirectory: ${{ github.workspace}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: pack
      run: dotnet pack -p:Configuration=Release_BasicVersion -p:Platform=x64 --output ${{ github.workspace}} ${{ github.workspace}}/src/Hybridizer.Runtime.CUDAImports.csproj

    - name: publish to nuget.org
      run: find . -name '*.nupkg' | xargs -i dotnet nuget push {} --api-key "${{ secrets.NUGET_PUBLISH }}" --source https://api.nuget.org/v3/index.json